language: java
jdk: oraclejdk8
install: true

notifications:
    email:
      recipients:
        - cniko446@gmail.com
        on_success: never # default: change
        on_failure: always # default: always
