language: java
jdk: oraclejdk8
install: true

script:
- ./mvnw clean install
- bash <(curl -s https://codecov.io/bash)
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
    email:
      recipients:
        - cniko446@gmail.com
        on_success: never # default: change
        on_failure: always # default: always
